apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.24
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            requests:
              cpu: '500m'
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ksrp-expose
  annotations:
    meta.ksrp-expose/default-spec: '{"selector":{"app":"nginx"},"ports":[{"port":80,"protocol":"TCP","targetPort":80}]}'
spec:
  sessionAffinity: None
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
